ALTER TABLE session DROP CONSTRAINT IF EXISTS "session_userId_fkey";
ALTER TABLE session DROP CONSTRAINT IF EXISTS session_active_organization_fk;
ALTER TABLE account DROP CONSTRAINT IF EXISTS "account_userId_fkey";
ALTER TABLE member DROP CONSTRAINT IF EXISTS "member_organizationId_fkey";
ALTER TABLE member DROP CONSTRAINT IF EXISTS "member_userId_fkey";
ALTER TABLE invitation DROP CONSTRAINT IF EXISTS "invitation_organizationId_fkey";
ALTER TABLE invitation DROP CONSTRAINT IF EXISTS "invitation_inviterId_fkey";
ALTER TABLE "twoFactor" DROP CONSTRAINT IF EXISTS "twoFactor_userId_fkey";
ALTER TABLE wpa_admin_accounts DROP CONSTRAINT IF EXISTS wpa_admin_accounts_user_id_fkey;

ALTER TABLE "user" ALTER COLUMN id DROP DEFAULT;
ALTER TABLE "user" ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE session ALTER COLUMN id DROP DEFAULT;
ALTER TABLE session ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE session ALTER COLUMN "userId" TYPE text USING "userId"::text;
ALTER TABLE session ALTER COLUMN "activeOrganizationId" TYPE text USING "activeOrganizationId"::text;
ALTER TABLE account ALTER COLUMN id DROP DEFAULT;
ALTER TABLE account ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE account ALTER COLUMN "userId" TYPE text USING "userId"::text;
ALTER TABLE verification ALTER COLUMN id DROP DEFAULT;
ALTER TABLE verification ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE organization ALTER COLUMN id DROP DEFAULT;
ALTER TABLE organization ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE member ALTER COLUMN id DROP DEFAULT;
ALTER TABLE member ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE member ALTER COLUMN "organizationId" TYPE text USING "organizationId"::text;
ALTER TABLE member ALTER COLUMN "userId" TYPE text USING "userId"::text;
ALTER TABLE invitation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE invitation ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE invitation ALTER COLUMN "organizationId" TYPE text USING "organizationId"::text;
ALTER TABLE invitation ALTER COLUMN "inviterId" TYPE text USING "inviterId"::text;
ALTER TABLE "twoFactor" ALTER COLUMN id DROP DEFAULT;
ALTER TABLE "twoFactor" ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE "twoFactor" ALTER COLUMN "userId" TYPE text USING "userId"::text;
ALTER TABLE wpa_admin_accounts ALTER COLUMN user_id TYPE text USING user_id::text;

ALTER TABLE session ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE session ADD CONSTRAINT session_active_organization_fk FOREIGN KEY ("activeOrganizationId") REFERENCES organization(id) ON DELETE SET NULL;
ALTER TABLE account ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE member ADD CONSTRAINT "member_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE member ADD CONSTRAINT "member_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE invitation ADD CONSTRAINT "invitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES organization(id) ON DELETE CASCADE;
ALTER TABLE invitation ADD CONSTRAINT "invitation_inviterId_fkey" FOREIGN KEY ("inviterId") REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE "twoFactor" ADD CONSTRAINT "twoFactor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE;
ALTER TABLE wpa_admin_accounts ADD CONSTRAINT wpa_admin_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;
