import { useEffect, useMemo, useState } from 'react';
import { Check, ClipboardCheck, Save, UserCheck, X } from 'lucide-react';
import { apiFetch, jsonRequest, privilegedApiFetch } from './api';

type Finding = { fingerprint: string; title: string; description?: string; severity: string; category?: string; pageUrl?: string; remediation?: string; evidence?: unknown[]; source?: { name?: string; version?: string } };
type Decision = { decision: 'accepted' | 'rejected' | 'edited'; priority: 'p0' | 'p1' | 'p2' | 'p3'; rationale?: string; edits?: Partial<Finding> };
type Review = { id: string; status: string; workspaceId: string; sourceReportId: string; scopePageUrls: string[]; assignedTo?: string; dueAt: string; findings?: Finding[]; decisions?: Record<string, Decision>; roadmap?: unknown[]; expertReportId?: string };

export default function ExpertReviewConsole({ actorId, canFinalize, canPublish }: { actorId?: string; canFinalize: boolean; canPublish: boolean }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [active, setActive] = useState<Review | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { const data = await apiFetch<{ reviews: Review[] }>('/api/v1/admin/expert-reviews'); setReviews(data.reviews); };
  useEffect(() => { void load().catch((e) => setError(e.message)); }, []);
  async function open(review: Review) { const detail = await apiFetch<{ review: Review }>(`/api/v1/admin/expert-reviews/${review.id}`); setActive(detail.review); }
  async function claim() { if (!active) return; const authorization = confirmedMutation('claiming this Expert Review'); if (!authorization) return; setBusy('claim'); try { const result = await apiFetch<{ review: Review }>(`/api/v1/admin/expert-reviews/${active.id}/claim`, jsonRequest('POST', authorization)); setActive(result.review); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function decide(finding: Finding, decision: Decision['decision']) {
    if (!active) return;
    const rationale = decision === 'rejected' ? window.prompt('Why is this finding rejected?')?.trim() : '';
    if (decision === 'rejected' && !rationale) return;
    const current = active.decisions?.[finding.fingerprint]; const body: Decision = { decision, priority: current?.priority || (finding.severity === 'critical' ? 'p0' : finding.severity === 'high' ? 'p1' : 'p2'), rationale };
    if (decision === 'edited') body.edits = { title: window.prompt('Reviewed title', finding.title)?.trim() || finding.title, severity: finding.severity, remediation: window.prompt('Reviewed remediation', finding.remediation || '')?.trim() || finding.remediation };
    const authorization = confirmedMutation(`${decision} decision on finding ${finding.fingerprint}`); if (!authorization) return;
    setBusy(finding.fingerprint);
    try { const result = await apiFetch<{ review: Review }>(`/api/v1/admin/expert-reviews/${active.id}/findings/${finding.fingerprint}`, jsonRequest('PUT', { ...body, ...authorization })); setActive(result.review); } catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  function confirmedMutation(action: string) {
    const reason = window.prompt(`Reason for ${action}`)?.trim();
    if (!reason || !window.confirm(`Confirm ${action} for review ${active?.id || ''}?`)) return null;
    return { reason, confirm: true as const };
  }
  async function finalize() { if (!active) return; const authorization = confirmedMutation('finalizing this reviewed report'); if (!authorization) return; setBusy('finalize'); try { await privilegedApiFetch(`/api/v1/admin/expert-reviews/${active.id}/finalize`, jsonRequest('POST', authorization)); await load(); setActive(null); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function roadmap() { if (!active) return; const raw = window.prompt('Roadmap JSON array', JSON.stringify(active.roadmap || [{ title: 'Fix highest-impact findings', description: '', owner: 'Engineering', effort: 'medium', horizon: 'now', findingFingerprints: [] }], null, 2)); if (!raw) return; const authorization = confirmedMutation('updating this remediation roadmap'); if (!authorization) return; setBusy('roadmap'); try { const result = await apiFetch<{ review: Review }>(`/api/v1/admin/expert-reviews/${active.id}/roadmap`, jsonRequest('PUT', { items: JSON.parse(raw), ...authorization })); setActive(result.review); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function publish() { if (!active) return; const authorization = confirmedMutation('publishing this Expert Review'); if (!authorization) return; setBusy('publish'); try { await privilegedApiFetch(`/api/v1/admin/expert-reviews/${active.id}/publish`, jsonRequest('POST', authorization)); await load(); setActive(null); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const progress = useMemo(() => active?.findings?.length ? Math.round((Object.keys(active.decisions || {}).length / active.findings.length) * 100) : 0, [active]);
  if (!active) return <div className="expert-console"><div className="portal-panel__title"><div><span>HUMAN APPROVAL</span><h2>Expert Review queue</h2></div><em>{reviews.length} requests</em></div>{error && <div className="portal-alert">{error}</div>}<div className="admin-records">{reviews.map((review) => <button className="admin-record expert-review-row" key={review.id} onClick={() => void open(review)}><ClipboardCheck /><span><b>{review.status.replaceAll('_', ' ')}</b><small>{review.workspaceId} · {review.scopePageUrls.length} pages</small></span><em>{new Date(review.dueAt).toLocaleDateString()}</em></button>)}</div></div>;
  return <div className="expert-console"><button className="expert-back" onClick={() => setActive(null)}>← Queue</button><div className="portal-panel__title"><div><span>REVIEW {active.id}</span><h2>{active.status.replaceAll('_', ' ')}</h2></div><b>{progress}% decided</b></div>{error && <div className="portal-alert">{error}</div>}{active.status === 'requested' && <button className="portal-primary" disabled={busy === 'claim'} onClick={() => void claim()}><UserCheck /> Claim review</button>}<div className="expert-findings">{active.findings?.map((finding) => { const decision = active.decisions?.[finding.fingerprint]; return <article className="expert-finding" key={finding.fingerprint}><header><div><small>{finding.category} · {finding.source?.name} {finding.source?.version}</small><h3>{finding.title}</h3><p>{finding.pageUrl}</p></div><b>{finding.severity}</b></header><p>{finding.description}</p><details><summary>Evidence & remediation</summary><pre>{JSON.stringify(finding.evidence || [], null, 2)}</pre><p>{finding.remediation}</p></details><footer><span>{decision ? `${decision.decision} · ${decision.priority}` : 'Awaiting decision'}</span><button disabled={busy === finding.fingerprint || active.assignedTo !== actorId} onClick={() => void decide(finding, 'accepted')}><Check /> Accept</button><button disabled={busy === finding.fingerprint || active.assignedTo !== actorId} onClick={() => void decide(finding, 'edited')}><Save /> Edit</button><button disabled={busy === finding.fingerprint || active.assignedTo !== actorId} onClick={() => void decide(finding, 'rejected')}><X /> Reject</button></footer></article>; })}</div>{active.status === 'in_review' && <button className="expert-finalize" disabled={busy === 'roadmap' || active.assignedTo !== actorId} onClick={() => void roadmap()}><Save /> Edit remediation roadmap</button>}{canFinalize && active.status === 'in_review' && <button className="portal-primary expert-finalize" disabled={busy === 'finalize' || progress < 100} onClick={() => void finalize()}><ClipboardCheck /> Finalize reviewed report</button>}{canPublish && active.status === 'ready_to_publish' && <button className="portal-primary expert-finalize" disabled={busy === 'publish'} onClick={() => void publish()}><ClipboardCheck /> Publish Expert Review</button>}</div>;
}
